### ISSUE TITLE
hey can you make a bot for this dashboard and make a tutorial

### ISSUE THREAD

**Issue by DEV1234simple** [SonMooSans/discord-bot-dashboard#2]

**Comment by SonMooSans** [comment]
Sorry for delay, I had made a example for the bot in Kotlin
[Check this repository](https://github.com/SonMooSans/discord-bot-dashboard-backend)

However if you need an example using discord.js or python then you must do it yourself 
For documentation for backend, check the above repo

The tutorial will not be out because you must take a few hours to write the whole backend
And it is not what a frontend template need
If you don’t know how to customize the UI feel free to open an issue
